package com.fanya.p2p.common.entity;

import java.io.Serializable;
import java.util.Date;

public class CapitalAccountBankcard implements Serializable{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column capital_account_bankcard.id
	 * @mbggenerated  Wed Nov 05 11:49:55 CST 2014
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column capital_account_bankcard.user_id
	 * @mbggenerated  Wed Nov 05 11:49:55 CST 2014
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column capital_account_bankcard.account_id
	 * @mbggenerated  Wed Nov 05 11:49:55 CST 2014
	 */
	private Long accountId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column capital_account_bankcard.card_no
	 * @mbggenerated  Wed Nov 05 11:49:55 CST 2014
	 */
	private String cardNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column capital_account_bankcard.card_type
	 * @mbggenerated  Wed Nov 05 11:49:55 CST 2014
	 */
	private String cardType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column capital_account_bankcard.bank_code
	 * @mbggenerated  Wed Nov 05 11:49:55 CST 2014
	 */
	private String bankCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column capital_account_bankcard.is_master
	 * @mbggenerated  Wed Nov 05 11:49:55 CST 2014
	 */
	private Boolean isMaster;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column capital_account_bankcard.state
	 * @mbggenerated  Wed Nov 05 11:49:55 CST 2014
	 */
	private String state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column capital_account_bankcard.created_time
	 * @mbggenerated  Wed Nov 05 11:49:55 CST 2014
	 */
	private Date createdTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column capital_account_bankcard.id
	 * @return  the value of capital_account_bankcard.id
	 * @mbggenerated  Wed Nov 05 11:49:55 CST 2014
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column capital_account_bankcard.id
	 * @param id  the value for capital_account_bankcard.id
	 * @mbggenerated  Wed Nov 05 11:49:55 CST 2014
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column capital_account_bankcard.user_id
	 * @return  the value of capital_account_bankcard.user_id
	 * @mbggenerated  Wed Nov 05 11:49:55 CST 2014
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column capital_account_bankcard.user_id
	 * @param userId  the value for capital_account_bankcard.user_id
	 * @mbggenerated  Wed Nov 05 11:49:55 CST 2014
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column capital_account_bankcard.account_id
	 * @return  the value of capital_account_bankcard.account_id
	 * @mbggenerated  Wed Nov 05 11:49:55 CST 2014
	 */
	public Long getAccountId() {
		return accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column capital_account_bankcard.account_id
	 * @param accountId  the value for capital_account_bankcard.account_id
	 * @mbggenerated  Wed Nov 05 11:49:55 CST 2014
	 */
	public void setAccountId(Long accountId) {
		this.accountId = accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column capital_account_bankcard.card_no
	 * @return  the value of capital_account_bankcard.card_no
	 * @mbggenerated  Wed Nov 05 11:49:55 CST 2014
	 */
	public String getCardNo() {
		return cardNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column capital_account_bankcard.card_no
	 * @param cardNo  the value for capital_account_bankcard.card_no
	 * @mbggenerated  Wed Nov 05 11:49:55 CST 2014
	 */
	public void setCardNo(String cardNo) {
		this.cardNo = cardNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column capital_account_bankcard.card_type
	 * @return  the value of capital_account_bankcard.card_type
	 * @mbggenerated  Wed Nov 05 11:49:55 CST 2014
	 */
	public String getCardType() {
		return cardType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column capital_account_bankcard.card_type
	 * @param cardType  the value for capital_account_bankcard.card_type
	 * @mbggenerated  Wed Nov 05 11:49:55 CST 2014
	 */
	public void setCardType(String cardType) {
		this.cardType = cardType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column capital_account_bankcard.bank_code
	 * @return  the value of capital_account_bankcard.bank_code
	 * @mbggenerated  Wed Nov 05 11:49:55 CST 2014
	 */
	public String getBankCode() {
		return bankCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column capital_account_bankcard.bank_code
	 * @param bankCode  the value for capital_account_bankcard.bank_code
	 * @mbggenerated  Wed Nov 05 11:49:55 CST 2014
	 */
	public void setBankCode(String bankCode) {
		this.bankCode = bankCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column capital_account_bankcard.is_master
	 * @return  the value of capital_account_bankcard.is_master
	 * @mbggenerated  Wed Nov 05 11:49:55 CST 2014
	 */
	public Boolean getIsMaster() {
		return isMaster;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column capital_account_bankcard.is_master
	 * @param isMaster  the value for capital_account_bankcard.is_master
	 * @mbggenerated  Wed Nov 05 11:49:55 CST 2014
	 */
	public void setIsMaster(Boolean isMaster) {
		this.isMaster = isMaster;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column capital_account_bankcard.state
	 * @return  the value of capital_account_bankcard.state
	 * @mbggenerated  Wed Nov 05 11:49:55 CST 2014
	 */
	public String getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column capital_account_bankcard.state
	 * @param state  the value for capital_account_bankcard.state
	 * @mbggenerated  Wed Nov 05 11:49:55 CST 2014
	 */
	public void setState(String state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column capital_account_bankcard.created_time
	 * @return  the value of capital_account_bankcard.created_time
	 * @mbggenerated  Wed Nov 05 11:49:55 CST 2014
	 */
	public Date getCreatedTime() {
		return createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column capital_account_bankcard.created_time
	 * @param createdTime  the value for capital_account_bankcard.created_time
	 * @mbggenerated  Wed Nov 05 11:49:55 CST 2014
	 */
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        CapitalAccountBankcard card = (CapitalAccountBankcard) o;

        if (id != null ? !id.equals(card.id) : card.id != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        return id != null ? id.hashCode() : 0;
    }

    @Override
    public String toString() {
        return "CapitalAccountBankcard{" +
                "id=" + id +
                ", userId=" + userId +
                ", accountId=" + accountId +
                ", cardNo='" + cardNo + '\'' +
                ", cardType='" + cardType + '\'' +
                ", state='" + state + '\'' +
                ", bankCode'=" + bankCode + '\'' +
                ", isMaster=" +isMaster +
                ",createdTime="+createdTime +
                '}';
    }
}