package com.fanya.p2p.common.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class LoanReturnPay implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_return_pay.id
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_return_pay.loan_id
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    private Long loanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_return_pay.loan_rf_id
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    private Long loanRfId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_return_pay.user_id
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_return_pay.amount
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_return_pay.state
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_return_pay.return_method
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    private String returnMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_return_pay.created_time
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    private Date createdTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_return_pay.id
     *
     * @return the value of loan_return_pay.id
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_return_pay.id
     *
     * @param id the value for loan_return_pay.id
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_return_pay.loan_id
     *
     * @return the value of loan_return_pay.loan_id
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public Long getLoanId() {
        return loanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_return_pay.loan_id
     *
     * @param loanId the value for loan_return_pay.loan_id
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public void setLoanId(Long loanId) {
        this.loanId = loanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_return_pay.loan_rf_id
     *
     * @return the value of loan_return_pay.loan_rf_id
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public Long getLoanRfId() {
        return loanRfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_return_pay.loan_rf_id
     *
     * @param loanRfId the value for loan_return_pay.loan_rf_id
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public void setLoanRfId(Long loanRfId) {
        this.loanRfId = loanRfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_return_pay.user_id
     *
     * @return the value of loan_return_pay.user_id
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_return_pay.user_id
     *
     * @param userId the value for loan_return_pay.user_id
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_return_pay.amount
     *
     * @return the value of loan_return_pay.amount
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_return_pay.amount
     *
     * @param amount the value for loan_return_pay.amount
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_return_pay.state
     *
     * @return the value of loan_return_pay.state
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_return_pay.state
     *
     * @param state the value for loan_return_pay.state
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_return_pay.return_method
     *
     * @return the value of loan_return_pay.return_method
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public String getReturnMethod() {
        return returnMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_return_pay.return_method
     *
     * @param returnMethod the value for loan_return_pay.return_method
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public void setReturnMethod(String returnMethod) {
        this.returnMethod = returnMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_return_pay.created_time
     *
     * @return the value of loan_return_pay.created_time
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_return_pay.created_time
     *
     * @param createdTime the value for loan_return_pay.created_time
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        LoanReturnPay loanReturnPay = (LoanReturnPay) o;

        if (id != null ? !id.equals(loanReturnPay.id) : loanReturnPay.id != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        return id != null ? id.hashCode() : 0;
    }

    @Override
    public String toString() {
        return "LoanReturnPay{" +
                "id=" + id +
                ", loanId=" + loanId +
                ", loanRfId=" + loanRfId +
                ", userId=" + userId +
                ", amount=" + amount +
                ", state='" + state + '\'' +
                ", returnMethod='" + returnMethod + '\'' +
                ", createdTime=" + createdTime +
                '}';
    }
}