package com.fanya.p2p.common.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class LoanReturnFlow implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_return_flow.id
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_return_flow.loan_id
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    private Long loanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_return_flow.expect_amount
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    private BigDecimal expectAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_return_flow.amount
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_return_flow.expect_principal
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    private BigDecimal expectPrincipal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_return_flow.principal
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    private BigDecimal principal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_return_flow.expect_interest
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    private BigDecimal expectInterest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_return_flow.interest
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    private BigDecimal interest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_return_flow.expect_date
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    private Date expectDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_return_flow.real_date
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    private Date realDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_return_flow.state
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_return_flow.created_time
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_return_flow.last_update_time
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_return_flow.remark
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_return_flow.id
     *
     * @return the value of loan_return_flow.id
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_return_flow.id
     *
     * @param id the value for loan_return_flow.id
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_return_flow.loan_id
     *
     * @return the value of loan_return_flow.loan_id
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public Long getLoanId() {
        return loanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_return_flow.loan_id
     *
     * @param loanId the value for loan_return_flow.loan_id
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public void setLoanId(Long loanId) {
        this.loanId = loanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_return_flow.expect_amount
     *
     * @return the value of loan_return_flow.expect_amount
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public BigDecimal getExpectAmount() {
        return expectAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_return_flow.expect_amount
     *
     * @param expectAmount the value for loan_return_flow.expect_amount
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public void setExpectAmount(BigDecimal expectAmount) {
        this.expectAmount = expectAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_return_flow.amount
     *
     * @return the value of loan_return_flow.amount
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_return_flow.amount
     *
     * @param amount the value for loan_return_flow.amount
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_return_flow.expect_principal
     *
     * @return the value of loan_return_flow.expect_principal
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public BigDecimal getExpectPrincipal() {
        return expectPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_return_flow.expect_principal
     *
     * @param expectPrincipal the value for loan_return_flow.expect_principal
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public void setExpectPrincipal(BigDecimal expectPrincipal) {
        this.expectPrincipal = expectPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_return_flow.principal
     *
     * @return the value of loan_return_flow.principal
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public BigDecimal getPrincipal() {
        return principal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_return_flow.principal
     *
     * @param principal the value for loan_return_flow.principal
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public void setPrincipal(BigDecimal principal) {
        this.principal = principal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_return_flow.expect_interest
     *
     * @return the value of loan_return_flow.expect_interest
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public BigDecimal getExpectInterest() {
        return expectInterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_return_flow.expect_interest
     *
     * @param expectInterest the value for loan_return_flow.expect_interest
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public void setExpectInterest(BigDecimal expectInterest) {
        this.expectInterest = expectInterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_return_flow.interest
     *
     * @return the value of loan_return_flow.interest
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public BigDecimal getInterest() {
        return interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_return_flow.interest
     *
     * @param interest the value for loan_return_flow.interest
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public void setInterest(BigDecimal interest) {
        this.interest = interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_return_flow.expect_date
     *
     * @return the value of loan_return_flow.expect_date
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public Date getExpectDate() {
        return expectDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_return_flow.expect_date
     *
     * @param expectDate the value for loan_return_flow.expect_date
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public void setExpectDate(Date expectDate) {
        this.expectDate = expectDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_return_flow.real_date
     *
     * @return the value of loan_return_flow.real_date
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public Date getRealDate() {
        return realDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_return_flow.real_date
     *
     * @param realDate the value for loan_return_flow.real_date
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public void setRealDate(Date realDate) {
        this.realDate = realDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_return_flow.state
     *
     * @return the value of loan_return_flow.state
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_return_flow.state
     *
     * @param state the value for loan_return_flow.state
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_return_flow.created_time
     *
     * @return the value of loan_return_flow.created_time
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_return_flow.created_time
     *
     * @param createdTime the value for loan_return_flow.created_time
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_return_flow.last_update_time
     *
     * @return the value of loan_return_flow.last_update_time
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_return_flow.last_update_time
     *
     * @param lastUpdateTime the value for loan_return_flow.last_update_time
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_return_flow.remark
     *
     * @return the value of loan_return_flow.remark
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_return_flow.remark
     *
     * @param remark the value for loan_return_flow.remark
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        LoanReturnFlow loanReturnFlow = (LoanReturnFlow) o;

        if (id != null ? !id.equals(loanReturnFlow.id) : loanReturnFlow.id != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        return id != null ? id.hashCode() : 0;
    }

    @Override
    public String toString() {
        return "LoanReturnFlow{" +
                "id=" + id +
                ", loanId=" + loanId +
                ", expectAmount=" + expectAmount +
                ", amount=" + amount +
                ", expectPrincipal=" + expectPrincipal +
                ", principal=" + principal +
                ", expectInterest=" + expectInterest +
                ", interest=" + interest +
                ", expectDate=" + expectDate +
                ", realDate=" + realDate +
                ", state='" + state + '\'' +
                ", createdTime=" + createdTime +
                ", lastUpdateTime=" + lastUpdateTime +
                ", remark='" + remark + '\'' +
                '}';
    }
}