package com.fanya.p2p.common.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class LoanInterestExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table loan_interest
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table loan_interest
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table loan_interest
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_interest
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public LoanInterestExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_interest
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_interest
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_interest
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_interest
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_interest
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_interest
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_interest
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_interest
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_interest
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_interest
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table loan_interest
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andLoanIdIsNull() {
            addCriterion("loan_id is null");
            return (Criteria) this;
        }

        public Criteria andLoanIdIsNotNull() {
            addCriterion("loan_id is not null");
            return (Criteria) this;
        }

        public Criteria andLoanIdEqualTo(Long value) {
            addCriterion("loan_id =", value, "loanId");
            return (Criteria) this;
        }

        public Criteria andLoanIdNotEqualTo(Long value) {
            addCriterion("loan_id <>", value, "loanId");
            return (Criteria) this;
        }

        public Criteria andLoanIdGreaterThan(Long value) {
            addCriterion("loan_id >", value, "loanId");
            return (Criteria) this;
        }

        public Criteria andLoanIdGreaterThanOrEqualTo(Long value) {
            addCriterion("loan_id >=", value, "loanId");
            return (Criteria) this;
        }

        public Criteria andLoanIdLessThan(Long value) {
            addCriterion("loan_id <", value, "loanId");
            return (Criteria) this;
        }

        public Criteria andLoanIdLessThanOrEqualTo(Long value) {
            addCriterion("loan_id <=", value, "loanId");
            return (Criteria) this;
        }

        public Criteria andLoanIdIn(List<Long> values) {
            addCriterion("loan_id in", values, "loanId");
            return (Criteria) this;
        }

        public Criteria andLoanIdNotIn(List<Long> values) {
            addCriterion("loan_id not in", values, "loanId");
            return (Criteria) this;
        }

        public Criteria andLoanIdBetween(Long value1, Long value2) {
            addCriterion("loan_id between", value1, value2, "loanId");
            return (Criteria) this;
        }

        public Criteria andLoanIdNotBetween(Long value1, Long value2) {
            addCriterion("loan_id not between", value1, value2, "loanId");
            return (Criteria) this;
        }

        public Criteria andInterestLifecycleTypeIsNull() {
            addCriterion("interest_lifecycle_type is null");
            return (Criteria) this;
        }

        public Criteria andInterestLifecycleTypeIsNotNull() {
            addCriterion("interest_lifecycle_type is not null");
            return (Criteria) this;
        }

        public Criteria andInterestLifecycleTypeEqualTo(String value) {
            addCriterion("interest_lifecycle_type =", value, "interestLifecycleType");
            return (Criteria) this;
        }

        public Criteria andInterestLifecycleTypeNotEqualTo(String value) {
            addCriterion("interest_lifecycle_type <>", value, "interestLifecycleType");
            return (Criteria) this;
        }

        public Criteria andInterestLifecycleTypeGreaterThan(String value) {
            addCriterion("interest_lifecycle_type >", value, "interestLifecycleType");
            return (Criteria) this;
        }

        public Criteria andInterestLifecycleTypeGreaterThanOrEqualTo(String value) {
            addCriterion("interest_lifecycle_type >=", value, "interestLifecycleType");
            return (Criteria) this;
        }

        public Criteria andInterestLifecycleTypeLessThan(String value) {
            addCriterion("interest_lifecycle_type <", value, "interestLifecycleType");
            return (Criteria) this;
        }

        public Criteria andInterestLifecycleTypeLessThanOrEqualTo(String value) {
            addCriterion("interest_lifecycle_type <=", value, "interestLifecycleType");
            return (Criteria) this;
        }

        public Criteria andInterestLifecycleTypeLike(String value) {
            addCriterion("interest_lifecycle_type like", value, "interestLifecycleType");
            return (Criteria) this;
        }

        public Criteria andInterestLifecycleTypeNotLike(String value) {
            addCriterion("interest_lifecycle_type not like", value, "interestLifecycleType");
            return (Criteria) this;
        }

        public Criteria andInterestLifecycleTypeIn(List<String> values) {
            addCriterion("interest_lifecycle_type in", values, "interestLifecycleType");
            return (Criteria) this;
        }

        public Criteria andInterestLifecycleTypeNotIn(List<String> values) {
            addCriterion("interest_lifecycle_type not in", values, "interestLifecycleType");
            return (Criteria) this;
        }

        public Criteria andInterestLifecycleTypeBetween(String value1, String value2) {
            addCriterion("interest_lifecycle_type between", value1, value2, "interestLifecycleType");
            return (Criteria) this;
        }

        public Criteria andInterestLifecycleTypeNotBetween(String value1, String value2) {
            addCriterion("interest_lifecycle_type not between", value1, value2, "interestLifecycleType");
            return (Criteria) this;
        }

        public Criteria andBeginInterestDateIsNull() {
            addCriterion("begin_interest_date is null");
            return (Criteria) this;
        }

        public Criteria andBeginInterestDateIsNotNull() {
            addCriterion("begin_interest_date is not null");
            return (Criteria) this;
        }

        public Criteria andBeginInterestDateEqualTo(Date value) {
            addCriterionForJDBCDate("begin_interest_date =", value, "beginInterestDate");
            return (Criteria) this;
        }

        public Criteria andBeginInterestDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("begin_interest_date <>", value, "beginInterestDate");
            return (Criteria) this;
        }

        public Criteria andBeginInterestDateGreaterThan(Date value) {
            addCriterionForJDBCDate("begin_interest_date >", value, "beginInterestDate");
            return (Criteria) this;
        }

        public Criteria andBeginInterestDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("begin_interest_date >=", value, "beginInterestDate");
            return (Criteria) this;
        }

        public Criteria andBeginInterestDateLessThan(Date value) {
            addCriterionForJDBCDate("begin_interest_date <", value, "beginInterestDate");
            return (Criteria) this;
        }

        public Criteria andBeginInterestDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("begin_interest_date <=", value, "beginInterestDate");
            return (Criteria) this;
        }

        public Criteria andBeginInterestDateIn(List<Date> values) {
            addCriterionForJDBCDate("begin_interest_date in", values, "beginInterestDate");
            return (Criteria) this;
        }

        public Criteria andBeginInterestDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("begin_interest_date not in", values, "beginInterestDate");
            return (Criteria) this;
        }

        public Criteria andBeginInterestDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("begin_interest_date between", value1, value2, "beginInterestDate");
            return (Criteria) this;
        }

        public Criteria andBeginInterestDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("begin_interest_date not between", value1, value2, "beginInterestDate");
            return (Criteria) this;
        }

        public Criteria andTermInterestDateIsNull() {
            addCriterion("term_interest_date is null");
            return (Criteria) this;
        }

        public Criteria andTermInterestDateIsNotNull() {
            addCriterion("term_interest_date is not null");
            return (Criteria) this;
        }

        public Criteria andTermInterestDateEqualTo(Date value) {
            addCriterionForJDBCDate("term_interest_date =", value, "termInterestDate");
            return (Criteria) this;
        }

        public Criteria andTermInterestDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("term_interest_date <>", value, "termInterestDate");
            return (Criteria) this;
        }

        public Criteria andTermInterestDateGreaterThan(Date value) {
            addCriterionForJDBCDate("term_interest_date >", value, "termInterestDate");
            return (Criteria) this;
        }

        public Criteria andTermInterestDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("term_interest_date >=", value, "termInterestDate");
            return (Criteria) this;
        }

        public Criteria andTermInterestDateLessThan(Date value) {
            addCriterionForJDBCDate("term_interest_date <", value, "termInterestDate");
            return (Criteria) this;
        }

        public Criteria andTermInterestDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("term_interest_date <=", value, "termInterestDate");
            return (Criteria) this;
        }

        public Criteria andTermInterestDateIn(List<Date> values) {
            addCriterionForJDBCDate("term_interest_date in", values, "termInterestDate");
            return (Criteria) this;
        }

        public Criteria andTermInterestDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("term_interest_date not in", values, "termInterestDate");
            return (Criteria) this;
        }

        public Criteria andTermInterestDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("term_interest_date between", value1, value2, "termInterestDate");
            return (Criteria) this;
        }

        public Criteria andTermInterestDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("term_interest_date not between", value1, value2, "termInterestDate");
            return (Criteria) this;
        }

        public Criteria andInterestRateIsNull() {
            addCriterion("interest_rate is null");
            return (Criteria) this;
        }

        public Criteria andInterestRateIsNotNull() {
            addCriterion("interest_rate is not null");
            return (Criteria) this;
        }

        public Criteria andInterestRateEqualTo(BigDecimal value) {
            addCriterion("interest_rate =", value, "interestRate");
            return (Criteria) this;
        }

        public Criteria andInterestRateNotEqualTo(BigDecimal value) {
            addCriterion("interest_rate <>", value, "interestRate");
            return (Criteria) this;
        }

        public Criteria andInterestRateGreaterThan(BigDecimal value) {
            addCriterion("interest_rate >", value, "interestRate");
            return (Criteria) this;
        }

        public Criteria andInterestRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("interest_rate >=", value, "interestRate");
            return (Criteria) this;
        }

        public Criteria andInterestRateLessThan(BigDecimal value) {
            addCriterion("interest_rate <", value, "interestRate");
            return (Criteria) this;
        }

        public Criteria andInterestRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("interest_rate <=", value, "interestRate");
            return (Criteria) this;
        }

        public Criteria andInterestRateIn(List<BigDecimal> values) {
            addCriterion("interest_rate in", values, "interestRate");
            return (Criteria) this;
        }

        public Criteria andInterestRateNotIn(List<BigDecimal> values) {
            addCriterion("interest_rate not in", values, "interestRate");
            return (Criteria) this;
        }

        public Criteria andInterestRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("interest_rate between", value1, value2, "interestRate");
            return (Criteria) this;
        }

        public Criteria andInterestRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("interest_rate not between", value1, value2, "interestRate");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("state like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("state not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("created_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("created_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(Date value) {
            addCriterion("created_time =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(Date value) {
            addCriterion("created_time <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(Date value) {
            addCriterion("created_time >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("created_time >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(Date value) {
            addCriterion("created_time <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("created_time <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<Date> values) {
            addCriterion("created_time in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<Date> values) {
            addCriterion("created_time not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(Date value1, Date value2) {
            addCriterion("created_time between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("created_time not between", value1, value2, "createdTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table loan_interest
     *
     * @mbggenerated do_not_delete_during_merge Wed Nov 05 12:06:21 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table loan_interest
     *
     * @mbggenerated Wed Nov 05 12:06:21 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}