package com.fanya.p2p.common.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class OrderPay implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pay.id
     *
     * @mbggenerated Wed Nov 05 12:13:35 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pay.order_id
     *
     * @mbggenerated Wed Nov 05 12:13:35 CST 2014
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pay.user_id
     *
     * @mbggenerated Wed Nov 05 12:13:35 CST 2014
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pay.pay_way
     *
     * @mbggenerated Wed Nov 05 12:13:35 CST 2014
     */
    private String payWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pay.amount
     *
     * @mbggenerated Wed Nov 05 12:13:35 CST 2014
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pay.state
     *
     * @mbggenerated Wed Nov 05 12:13:35 CST 2014
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pay.remark
     *
     * @mbggenerated Wed Nov 05 12:13:35 CST 2014
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pay.created_time
     *
     * @mbggenerated Wed Nov 05 12:13:35 CST 2014
     */
    private Date createdTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pay.id
     *
     * @return the value of order_pay.id
     *
     * @mbggenerated Wed Nov 05 12:13:35 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pay.id
     *
     * @param id the value for order_pay.id
     *
     * @mbggenerated Wed Nov 05 12:13:35 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pay.order_id
     *
     * @return the value of order_pay.order_id
     *
     * @mbggenerated Wed Nov 05 12:13:35 CST 2014
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pay.order_id
     *
     * @param orderId the value for order_pay.order_id
     *
     * @mbggenerated Wed Nov 05 12:13:35 CST 2014
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pay.user_id
     *
     * @return the value of order_pay.user_id
     *
     * @mbggenerated Wed Nov 05 12:13:35 CST 2014
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pay.user_id
     *
     * @param userId the value for order_pay.user_id
     *
     * @mbggenerated Wed Nov 05 12:13:35 CST 2014
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pay.pay_way
     *
     * @return the value of order_pay.pay_way
     *
     * @mbggenerated Wed Nov 05 12:13:35 CST 2014
     */
    public String getPayWay() {
        return payWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pay.pay_way
     *
     * @param payWay the value for order_pay.pay_way
     *
     * @mbggenerated Wed Nov 05 12:13:35 CST 2014
     */
    public void setPayWay(String payWay) {
        this.payWay = payWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pay.amount
     *
     * @return the value of order_pay.amount
     *
     * @mbggenerated Wed Nov 05 12:13:35 CST 2014
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pay.amount
     *
     * @param amount the value for order_pay.amount
     *
     * @mbggenerated Wed Nov 05 12:13:35 CST 2014
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pay.state
     *
     * @return the value of order_pay.state
     *
     * @mbggenerated Wed Nov 05 12:13:35 CST 2014
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pay.state
     *
     * @param state the value for order_pay.state
     *
     * @mbggenerated Wed Nov 05 12:13:35 CST 2014
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pay.remark
     *
     * @return the value of order_pay.remark
     *
     * @mbggenerated Wed Nov 05 12:13:35 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pay.remark
     *
     * @param remark the value for order_pay.remark
     *
     * @mbggenerated Wed Nov 05 12:13:35 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pay.created_time
     *
     * @return the value of order_pay.created_time
     *
     * @mbggenerated Wed Nov 05 12:13:35 CST 2014
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pay.created_time
     *
     * @param createdTime the value for order_pay.created_time
     *
     * @mbggenerated Wed Nov 05 12:13:35 CST 2014
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        OrderPay orderPay = (OrderPay) o;

        if (id != null ? !id.equals(orderPay.id) : orderPay.id != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        return id != null ? id.hashCode() : 0;
    }

    @Override
    public String toString() {
        return "OrderPay{" +
                "id=" + id +
                ", orderId=" + orderId +
                ", userId=" + userId +
                ", payWay='" + payWay + '\'' +
                ", state='" + state + '\'' +
                ", amount=" + amount +
                ", remark='" + remark + '\'' +
                ", createdTime=" + createdTime +
                '}';
    }
}