package com.fanya.p2p.common.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProdAuditFlowExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table prod_audit_flow
     *
     * @mbggenerated Wed Nov 05 12:11:21 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table prod_audit_flow
     *
     * @mbggenerated Wed Nov 05 12:11:21 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table prod_audit_flow
     *
     * @mbggenerated Wed Nov 05 12:11:21 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_audit_flow
     *
     * @mbggenerated Wed Nov 05 12:11:21 CST 2014
     */
    public ProdAuditFlowExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_audit_flow
     *
     * @mbggenerated Wed Nov 05 12:11:21 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_audit_flow
     *
     * @mbggenerated Wed Nov 05 12:11:21 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_audit_flow
     *
     * @mbggenerated Wed Nov 05 12:11:21 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_audit_flow
     *
     * @mbggenerated Wed Nov 05 12:11:21 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_audit_flow
     *
     * @mbggenerated Wed Nov 05 12:11:21 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_audit_flow
     *
     * @mbggenerated Wed Nov 05 12:11:21 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_audit_flow
     *
     * @mbggenerated Wed Nov 05 12:11:21 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_audit_flow
     *
     * @mbggenerated Wed Nov 05 12:11:21 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_audit_flow
     *
     * @mbggenerated Wed Nov 05 12:11:21 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_audit_flow
     *
     * @mbggenerated Wed Nov 05 12:11:21 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table prod_audit_flow
     *
     * @mbggenerated Wed Nov 05 12:11:21 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProdIdIsNull() {
            addCriterion("prod_id is null");
            return (Criteria) this;
        }

        public Criteria andProdIdIsNotNull() {
            addCriterion("prod_id is not null");
            return (Criteria) this;
        }

        public Criteria andProdIdEqualTo(Long value) {
            addCriterion("prod_id =", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdNotEqualTo(Long value) {
            addCriterion("prod_id <>", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdGreaterThan(Long value) {
            addCriterion("prod_id >", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdGreaterThanOrEqualTo(Long value) {
            addCriterion("prod_id >=", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdLessThan(Long value) {
            addCriterion("prod_id <", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdLessThanOrEqualTo(Long value) {
            addCriterion("prod_id <=", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdIn(List<Long> values) {
            addCriterion("prod_id in", values, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdNotIn(List<Long> values) {
            addCriterion("prod_id not in", values, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdBetween(Long value1, Long value2) {
            addCriterion("prod_id between", value1, value2, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdNotBetween(Long value1, Long value2) {
            addCriterion("prod_id not between", value1, value2, "prodId");
            return (Criteria) this;
        }

        public Criteria andCurrentUserIdIsNull() {
            addCriterion("current_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCurrentUserIdIsNotNull() {
            addCriterion("current_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentUserIdEqualTo(Long value) {
            addCriterion("current_user_id =", value, "currentUserId");
            return (Criteria) this;
        }

        public Criteria andCurrentUserIdNotEqualTo(Long value) {
            addCriterion("current_user_id <>", value, "currentUserId");
            return (Criteria) this;
        }

        public Criteria andCurrentUserIdGreaterThan(Long value) {
            addCriterion("current_user_id >", value, "currentUserId");
            return (Criteria) this;
        }

        public Criteria andCurrentUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("current_user_id >=", value, "currentUserId");
            return (Criteria) this;
        }

        public Criteria andCurrentUserIdLessThan(Long value) {
            addCriterion("current_user_id <", value, "currentUserId");
            return (Criteria) this;
        }

        public Criteria andCurrentUserIdLessThanOrEqualTo(Long value) {
            addCriterion("current_user_id <=", value, "currentUserId");
            return (Criteria) this;
        }

        public Criteria andCurrentUserIdIn(List<Long> values) {
            addCriterion("current_user_id in", values, "currentUserId");
            return (Criteria) this;
        }

        public Criteria andCurrentUserIdNotIn(List<Long> values) {
            addCriterion("current_user_id not in", values, "currentUserId");
            return (Criteria) this;
        }

        public Criteria andCurrentUserIdBetween(Long value1, Long value2) {
            addCriterion("current_user_id between", value1, value2, "currentUserId");
            return (Criteria) this;
        }

        public Criteria andCurrentUserIdNotBetween(Long value1, Long value2) {
            addCriterion("current_user_id not between", value1, value2, "currentUserId");
            return (Criteria) this;
        }

        public Criteria andNextUserIdIsNull() {
            addCriterion("next_user_id is null");
            return (Criteria) this;
        }

        public Criteria andNextUserIdIsNotNull() {
            addCriterion("next_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andNextUserIdEqualTo(Long value) {
            addCriterion("next_user_id =", value, "nextUserId");
            return (Criteria) this;
        }

        public Criteria andNextUserIdNotEqualTo(Long value) {
            addCriterion("next_user_id <>", value, "nextUserId");
            return (Criteria) this;
        }

        public Criteria andNextUserIdGreaterThan(Long value) {
            addCriterion("next_user_id >", value, "nextUserId");
            return (Criteria) this;
        }

        public Criteria andNextUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("next_user_id >=", value, "nextUserId");
            return (Criteria) this;
        }

        public Criteria andNextUserIdLessThan(Long value) {
            addCriterion("next_user_id <", value, "nextUserId");
            return (Criteria) this;
        }

        public Criteria andNextUserIdLessThanOrEqualTo(Long value) {
            addCriterion("next_user_id <=", value, "nextUserId");
            return (Criteria) this;
        }

        public Criteria andNextUserIdIn(List<Long> values) {
            addCriterion("next_user_id in", values, "nextUserId");
            return (Criteria) this;
        }

        public Criteria andNextUserIdNotIn(List<Long> values) {
            addCriterion("next_user_id not in", values, "nextUserId");
            return (Criteria) this;
        }

        public Criteria andNextUserIdBetween(Long value1, Long value2) {
            addCriterion("next_user_id between", value1, value2, "nextUserId");
            return (Criteria) this;
        }

        public Criteria andNextUserIdNotBetween(Long value1, Long value2) {
            addCriterion("next_user_id not between", value1, value2, "nextUserId");
            return (Criteria) this;
        }

        public Criteria andNextRoleIdIsNull() {
            addCriterion("next_role_id is null");
            return (Criteria) this;
        }

        public Criteria andNextRoleIdIsNotNull() {
            addCriterion("next_role_id is not null");
            return (Criteria) this;
        }

        public Criteria andNextRoleIdEqualTo(Long value) {
            addCriterion("next_role_id =", value, "nextRoleId");
            return (Criteria) this;
        }

        public Criteria andNextRoleIdNotEqualTo(Long value) {
            addCriterion("next_role_id <>", value, "nextRoleId");
            return (Criteria) this;
        }

        public Criteria andNextRoleIdGreaterThan(Long value) {
            addCriterion("next_role_id >", value, "nextRoleId");
            return (Criteria) this;
        }

        public Criteria andNextRoleIdGreaterThanOrEqualTo(Long value) {
            addCriterion("next_role_id >=", value, "nextRoleId");
            return (Criteria) this;
        }

        public Criteria andNextRoleIdLessThan(Long value) {
            addCriterion("next_role_id <", value, "nextRoleId");
            return (Criteria) this;
        }

        public Criteria andNextRoleIdLessThanOrEqualTo(Long value) {
            addCriterion("next_role_id <=", value, "nextRoleId");
            return (Criteria) this;
        }

        public Criteria andNextRoleIdIn(List<Long> values) {
            addCriterion("next_role_id in", values, "nextRoleId");
            return (Criteria) this;
        }

        public Criteria andNextRoleIdNotIn(List<Long> values) {
            addCriterion("next_role_id not in", values, "nextRoleId");
            return (Criteria) this;
        }

        public Criteria andNextRoleIdBetween(Long value1, Long value2) {
            addCriterion("next_role_id between", value1, value2, "nextRoleId");
            return (Criteria) this;
        }

        public Criteria andNextRoleIdNotBetween(Long value1, Long value2) {
            addCriterion("next_role_id not between", value1, value2, "nextRoleId");
            return (Criteria) this;
        }

        public Criteria andNoteIsNull() {
            addCriterion("note is null");
            return (Criteria) this;
        }

        public Criteria andNoteIsNotNull() {
            addCriterion("note is not null");
            return (Criteria) this;
        }

        public Criteria andNoteEqualTo(String value) {
            addCriterion("note =", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotEqualTo(String value) {
            addCriterion("note <>", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThan(String value) {
            addCriterion("note >", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThanOrEqualTo(String value) {
            addCriterion("note >=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThan(String value) {
            addCriterion("note <", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThanOrEqualTo(String value) {
            addCriterion("note <=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLike(String value) {
            addCriterion("note like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotLike(String value) {
            addCriterion("note not like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteIn(List<String> values) {
            addCriterion("note in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotIn(List<String> values) {
            addCriterion("note not in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteBetween(String value1, String value2) {
            addCriterion("note between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotBetween(String value1, String value2) {
            addCriterion("note not between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andAuditResultIsNull() {
            addCriterion("audit_result is null");
            return (Criteria) this;
        }

        public Criteria andAuditResultIsNotNull() {
            addCriterion("audit_result is not null");
            return (Criteria) this;
        }

        public Criteria andAuditResultEqualTo(String value) {
            addCriterion("audit_result =", value, "auditResult");
            return (Criteria) this;
        }

        public Criteria andAuditResultNotEqualTo(String value) {
            addCriterion("audit_result <>", value, "auditResult");
            return (Criteria) this;
        }

        public Criteria andAuditResultGreaterThan(String value) {
            addCriterion("audit_result >", value, "auditResult");
            return (Criteria) this;
        }

        public Criteria andAuditResultGreaterThanOrEqualTo(String value) {
            addCriterion("audit_result >=", value, "auditResult");
            return (Criteria) this;
        }

        public Criteria andAuditResultLessThan(String value) {
            addCriterion("audit_result <", value, "auditResult");
            return (Criteria) this;
        }

        public Criteria andAuditResultLessThanOrEqualTo(String value) {
            addCriterion("audit_result <=", value, "auditResult");
            return (Criteria) this;
        }

        public Criteria andAuditResultLike(String value) {
            addCriterion("audit_result like", value, "auditResult");
            return (Criteria) this;
        }

        public Criteria andAuditResultNotLike(String value) {
            addCriterion("audit_result not like", value, "auditResult");
            return (Criteria) this;
        }

        public Criteria andAuditResultIn(List<String> values) {
            addCriterion("audit_result in", values, "auditResult");
            return (Criteria) this;
        }

        public Criteria andAuditResultNotIn(List<String> values) {
            addCriterion("audit_result not in", values, "auditResult");
            return (Criteria) this;
        }

        public Criteria andAuditResultBetween(String value1, String value2) {
            addCriterion("audit_result between", value1, value2, "auditResult");
            return (Criteria) this;
        }

        public Criteria andAuditResultNotBetween(String value1, String value2) {
            addCriterion("audit_result not between", value1, value2, "auditResult");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("created_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("created_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(Date value) {
            addCriterion("created_time =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(Date value) {
            addCriterion("created_time <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(Date value) {
            addCriterion("created_time >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("created_time >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(Date value) {
            addCriterion("created_time <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("created_time <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<Date> values) {
            addCriterion("created_time in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<Date> values) {
            addCriterion("created_time not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(Date value1, Date value2) {
            addCriterion("created_time between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("created_time not between", value1, value2, "createdTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table prod_audit_flow
     *
     * @mbggenerated do_not_delete_during_merge Wed Nov 05 12:11:21 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table prod_audit_flow
     *
     * @mbggenerated Wed Nov 05 12:11:21 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}