package com.fanya.p2p.common.entity;

import java.io.Serializable;

public class SysUser implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.id
	 * @mbggenerated  Wed Oct 15 15:48:30 CST 2014
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.organization_id
	 * @mbggenerated  Wed Oct 15 15:48:30 CST 2014
	 */
	private Long organizationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.username
	 * @mbggenerated  Wed Oct 15 15:48:30 CST 2014
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.email
	 * @mbggenerated  Wed Oct 15 15:48:30 CST 2014
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.mobile
	 * @mbggenerated  Wed Oct 15 15:48:30 CST 2014
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.invest_state
	 * @mbggenerated  Wed Oct 15 15:48:30 CST 2014
	 */
	private Integer investState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.loan_state
	 * @mbggenerated  Wed Oct 15 15:48:30 CST 2014
	 */
	private Integer loanState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.credit_rate
	 * @mbggenerated  Wed Oct 15 15:48:30 CST 2014
	 */
	private Integer creditRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.password
	 * @mbggenerated  Wed Oct 15 15:48:30 CST 2014
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.salt
	 * @mbggenerated  Wed Oct 15 15:48:30 CST 2014
	 */
	private String salt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.locked
	 * @mbggenerated  Wed Oct 15 15:48:30 CST 2014
	 */
	private Boolean locked;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.id
	 * @return  the value of sys_user.id
	 * @mbggenerated  Wed Oct 15 15:48:30 CST 2014
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.id
	 * @param id  the value for sys_user.id
	 * @mbggenerated  Wed Oct 15 15:48:30 CST 2014
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.organization_id
	 * @return  the value of sys_user.organization_id
	 * @mbggenerated  Wed Oct 15 15:48:30 CST 2014
	 */
	public Long getOrganizationId() {
		return organizationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.organization_id
	 * @param organizationId  the value for sys_user.organization_id
	 * @mbggenerated  Wed Oct 15 15:48:30 CST 2014
	 */
	public void setOrganizationId(Long organizationId) {
		this.organizationId = organizationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.username
	 * @return  the value of sys_user.username
	 * @mbggenerated  Wed Oct 15 15:48:30 CST 2014
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.username
	 * @param username  the value for sys_user.username
	 * @mbggenerated  Wed Oct 15 15:48:30 CST 2014
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.email
	 * @return  the value of sys_user.email
	 * @mbggenerated  Wed Oct 15 15:48:30 CST 2014
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.email
	 * @param email  the value for sys_user.email
	 * @mbggenerated  Wed Oct 15 15:48:30 CST 2014
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.mobile
	 * @return  the value of sys_user.mobile
	 * @mbggenerated  Wed Oct 15 15:48:30 CST 2014
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.mobile
	 * @param mobile  the value for sys_user.mobile
	 * @mbggenerated  Wed Oct 15 15:48:30 CST 2014
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.invest_state
	 * @return  the value of sys_user.invest_state
	 * @mbggenerated  Wed Oct 15 15:48:30 CST 2014
	 */
	public Integer getInvestState() {
		return investState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.invest_state
	 * @param investState  the value for sys_user.invest_state
	 * @mbggenerated  Wed Oct 15 15:48:30 CST 2014
	 */
	public void setInvestState(Integer investState) {
		this.investState = investState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.loan_state
	 * @return  the value of sys_user.loan_state
	 * @mbggenerated  Wed Oct 15 15:48:30 CST 2014
	 */
	public Integer getLoanState() {
		return loanState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.loan_state
	 * @param loanState  the value for sys_user.loan_state
	 * @mbggenerated  Wed Oct 15 15:48:30 CST 2014
	 */
	public void setLoanState(Integer loanState) {
		this.loanState = loanState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.credit_rate
	 * @return  the value of sys_user.credit_rate
	 * @mbggenerated  Wed Oct 15 15:48:30 CST 2014
	 */
	public Integer getCreditRate() {
		return creditRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.credit_rate
	 * @param creditRate  the value for sys_user.credit_rate
	 * @mbggenerated  Wed Oct 15 15:48:30 CST 2014
	 */
	public void setCreditRate(Integer creditRate) {
		this.creditRate = creditRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.password
	 * @return  the value of sys_user.password
	 * @mbggenerated  Wed Oct 15 15:48:30 CST 2014
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.password
	 * @param password  the value for sys_user.password
	 * @mbggenerated  Wed Oct 15 15:48:30 CST 2014
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.salt
	 * @return  the value of sys_user.salt
	 * @mbggenerated  Wed Oct 15 15:48:30 CST 2014
	 */
	public String getSalt() {
		return salt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.salt
	 * @param salt  the value for sys_user.salt
	 * @mbggenerated  Wed Oct 15 15:48:30 CST 2014
	 */
	public void setSalt(String salt) {
		this.salt = salt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.locked
	 * @return  the value of sys_user.locked
	 * @mbggenerated  Wed Oct 15 15:48:30 CST 2014
	 */
	public Boolean getLocked() {
		return locked;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.locked
	 * @param locked  the value for sys_user.locked
	 * @mbggenerated  Wed Oct 15 15:48:30 CST 2014
	 */
	public void setLocked(Boolean locked) {
		this.locked = locked;
	}

    public String getCredentialsSalt() {
        return username + salt;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        SysUser user = (SysUser) o;

        if (id != null ? !id.equals(user.id) : user.id != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        return id != null ? id.hashCode() : 0;
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", organizationId=" + organizationId +
                ", username='" + username + '\'' +
                ", password='" + password + '\'' +
                ", salt='" + salt + '\'' +
                ", locked=" + locked +
                '}';
    }
}