package com.fanya.p2p.core.user.dao;

import com.fanya.p2p.common.entity.SysUserAppRoles;
import com.fanya.p2p.common.entity.SysUserAppRolesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysUserAppRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_app_roles
     *
     * @mbggenerated Sun Oct 05 15:15:24 CST 2014
     */
    int countByExample(SysUserAppRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_app_roles
     *
     * @mbggenerated Sun Oct 05 15:15:24 CST 2014
     */
    int deleteByExample(SysUserAppRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_app_roles
     *
     * @mbggenerated Sun Oct 05 15:15:24 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_app_roles
     *
     * @mbggenerated Sun Oct 05 15:15:24 CST 2014
     */
    int insert(SysUserAppRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_app_roles
     *
     * @mbggenerated Sun Oct 05 15:15:24 CST 2014
     */
    int insertSelective(SysUserAppRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_app_roles
     *
     * @mbggenerated Sun Oct 05 15:15:24 CST 2014
     */
    List<SysUserAppRoles> selectByExample(SysUserAppRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_app_roles
     *
     * @mbggenerated Sun Oct 05 15:15:24 CST 2014
     */
    SysUserAppRoles selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_app_roles
     *
     * @mbggenerated Sun Oct 05 15:15:24 CST 2014
     */
    int updateByExampleSelective(@Param("record") SysUserAppRoles record, @Param("example") SysUserAppRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_app_roles
     *
     * @mbggenerated Sun Oct 05 15:15:24 CST 2014
     */
    int updateByExample(@Param("record") SysUserAppRoles record, @Param("example") SysUserAppRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_app_roles
     *
     * @mbggenerated Sun Oct 05 15:15:24 CST 2014
     */
    int updateByPrimaryKeySelective(SysUserAppRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_app_roles
     *
     * @mbggenerated Sun Oct 05 15:15:24 CST 2014
     */
    int updateByPrimaryKey(SysUserAppRoles record);
}