package com.fanya.p2p.core.account.dao;

import com.fanya.p2p.common.entity.CapitalAccount;
import com.fanya.p2p.common.entity.CapitalAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CapitalAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_account
     *
     * @mbggenerated Tue Oct 14 10:48:47 CST 2014
     */
    int countByExample(CapitalAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_account
     *
     * @mbggenerated Tue Oct 14 10:48:47 CST 2014
     */
    int deleteByExample(CapitalAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_account
     *
     * @mbggenerated Tue Oct 14 10:48:47 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_account
     *
     * @mbggenerated Tue Oct 14 10:48:47 CST 2014
     */
    int insert(CapitalAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_account
     *
     * @mbggenerated Tue Oct 14 10:48:47 CST 2014
     */
    int insertSelective(CapitalAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_account
     *
     * @mbggenerated Tue Oct 14 10:48:47 CST 2014
     */
    List<CapitalAccount> selectByExample(CapitalAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_account
     *
     * @mbggenerated Tue Oct 14 10:48:47 CST 2014
     */
    CapitalAccount selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_account
     *
     * @mbggenerated Tue Oct 14 10:48:47 CST 2014
     */
    int updateByExampleSelective(@Param("record") CapitalAccount record, @Param("example") CapitalAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_account
     *
     * @mbggenerated Tue Oct 14 10:48:47 CST 2014
     */
    int updateByExample(@Param("record") CapitalAccount record, @Param("example") CapitalAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_account
     *
     * @mbggenerated Tue Oct 14 10:48:47 CST 2014
     */
    int updateByPrimaryKeySelective(CapitalAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_account
     *
     * @mbggenerated Tue Oct 14 10:48:47 CST 2014
     */
    int updateByPrimaryKey(CapitalAccount record);
}