package com.fanya.p2p.core.account.dao;

import com.fanya.p2p.common.entity.CapitalAccountFlow;
import com.fanya.p2p.common.entity.CapitalAccountFlowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CapitalAccountFlowMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table capital_account_flow
	 * @mbggenerated  Wed Oct 15 10:00:09 CST 2014
	 */
	int countByExample(CapitalAccountFlowExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table capital_account_flow
	 * @mbggenerated  Wed Oct 15 10:00:09 CST 2014
	 */
	int deleteByExample(CapitalAccountFlowExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table capital_account_flow
	 * @mbggenerated  Wed Oct 15 10:00:09 CST 2014
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table capital_account_flow
	 * @mbggenerated  Wed Oct 15 10:00:09 CST 2014
	 */
	int insert(CapitalAccountFlow record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table capital_account_flow
	 * @mbggenerated  Wed Oct 15 10:00:09 CST 2014
	 */
	int insertSelective(CapitalAccountFlow record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table capital_account_flow
	 * @mbggenerated  Wed Oct 15 10:00:09 CST 2014
	 */
	List<CapitalAccountFlow> selectByExample(CapitalAccountFlowExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table capital_account_flow
	 * @mbggenerated  Wed Oct 15 10:00:09 CST 2014
	 */
	CapitalAccountFlow selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table capital_account_flow
	 * @mbggenerated  Wed Oct 15 10:00:09 CST 2014
	 */
	int updateByExampleSelective(@Param("record") CapitalAccountFlow record,
                                 @Param("example") CapitalAccountFlowExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table capital_account_flow
	 * @mbggenerated  Wed Oct 15 10:00:09 CST 2014
	 */
	int updateByExample(@Param("record") CapitalAccountFlow record,
                        @Param("example") CapitalAccountFlowExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table capital_account_flow
	 * @mbggenerated  Wed Oct 15 10:00:09 CST 2014
	 */
	int updateByPrimaryKeySelective(CapitalAccountFlow record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table capital_account_flow
	 * @mbggenerated  Wed Oct 15 10:00:09 CST 2014
	 */
	int updateByPrimaryKey(CapitalAccountFlow record);
}