package com.fanya.p2p.core.prod.dao;

import com.fanya.p2p.common.entity.PackageItem;
import com.fanya.p2p.common.entity.PackageItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PackageItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_item
     *
     * @mbggenerated Wed Nov 05 12:11:21 CST 2014
     */
    int countByExample(PackageItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_item
     *
     * @mbggenerated Wed Nov 05 12:11:21 CST 2014
     */
    int deleteByExample(PackageItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_item
     *
     * @mbggenerated Wed Nov 05 12:11:21 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_item
     *
     * @mbggenerated Wed Nov 05 12:11:21 CST 2014
     */
    int insert(PackageItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_item
     *
     * @mbggenerated Wed Nov 05 12:11:21 CST 2014
     */
    int insertSelective(PackageItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_item
     *
     * @mbggenerated Wed Nov 05 12:11:21 CST 2014
     */
    List<PackageItem> selectByExample(PackageItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_item
     *
     * @mbggenerated Wed Nov 05 12:11:21 CST 2014
     */
    PackageItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_item
     *
     * @mbggenerated Wed Nov 05 12:11:21 CST 2014
     */
    int updateByExampleSelective(@Param("record") PackageItem record, @Param("example") PackageItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_item
     *
     * @mbggenerated Wed Nov 05 12:11:21 CST 2014
     */
    int updateByExample(@Param("record") PackageItem record, @Param("example") PackageItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_item
     *
     * @mbggenerated Wed Nov 05 12:11:21 CST 2014
     */
    int updateByPrimaryKeySelective(PackageItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_item
     *
     * @mbggenerated Wed Nov 05 12:11:21 CST 2014
     */
    int updateByPrimaryKey(PackageItem record);
}