package com.fanya.p2p.core.prod.dao;

import com.fanya.p2p.common.entity.ProdAuditFlow;
import com.fanya.p2p.common.entity.ProdAuditFlowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProdAuditFlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_audit_flow
     *
     * @mbggenerated Wed Nov 05 12:11:21 CST 2014
     */
    int countByExample(ProdAuditFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_audit_flow
     *
     * @mbggenerated Wed Nov 05 12:11:21 CST 2014
     */
    int deleteByExample(ProdAuditFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_audit_flow
     *
     * @mbggenerated Wed Nov 05 12:11:21 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_audit_flow
     *
     * @mbggenerated Wed Nov 05 12:11:21 CST 2014
     */
    int insert(ProdAuditFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_audit_flow
     *
     * @mbggenerated Wed Nov 05 12:11:21 CST 2014
     */
    int insertSelective(ProdAuditFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_audit_flow
     *
     * @mbggenerated Wed Nov 05 12:11:21 CST 2014
     */
    List<ProdAuditFlow> selectByExample(ProdAuditFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_audit_flow
     *
     * @mbggenerated Wed Nov 05 12:11:21 CST 2014
     */
    ProdAuditFlow selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_audit_flow
     *
     * @mbggenerated Wed Nov 05 12:11:21 CST 2014
     */
    int updateByExampleSelective(@Param("record") ProdAuditFlow record, @Param("example") ProdAuditFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_audit_flow
     *
     * @mbggenerated Wed Nov 05 12:11:21 CST 2014
     */
    int updateByExample(@Param("record") ProdAuditFlow record, @Param("example") ProdAuditFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_audit_flow
     *
     * @mbggenerated Wed Nov 05 12:11:21 CST 2014
     */
    int updateByPrimaryKeySelective(ProdAuditFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_audit_flow
     *
     * @mbggenerated Wed Nov 05 12:11:21 CST 2014
     */
    int updateByPrimaryKey(ProdAuditFlow record);
}